### PR TITLE
Improve documentation for Threat Intel functions  

### PR DESCRIPTION
**Pull request by zeyadtmi**
## Changes proposed

Enhanced clarity, detail, and structure of docstrings across various Threat Intel module functions. This includes better descriptions of parameters, return values, side effects, and example usage where applicable. The goal is to improve code readability, maintainability, and ease of use for future development and API consumers.

## Check List (Check all the applicable boxes) 

- [ X ] My code follows the code style of this project.
- [ X ] My change requires changes to the documentation.
- [ X ] I have updated the documentation accordingly.
- [ X ] All new and existing tests passed.
- [ X ] This PR does not contain plagiarized content.
- [ X ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

I am not sure if this PR overlaps with Sekhar's PR, but I do not think there should be a conflict.

### CODE REVIEW

**Review by eldraco — COMMENTED** [review]
This is good thanks @zeyadtmi. But can you add a little of documentation regarding the main functions (CIRCL and Spamhaus access) to the docs? So in docs/ there is a file called detection_modules.md. In that file there is a section called "Threat Intelligence Module". Can you add there the new documentation in a clear way? thanks

**Review by zeyadtmi — COMMENTED** [review]
This is my complete documentation on the threat intelligence module!

**Review by eldraco — COMMENTED** [review]
@zeyadtmi your PR fails the tests due to a wrong identation. I don't understand, you said you run the tests and that the tests passed. And also @alya was asking all new contributors to provide a screenshot about this due to people not running tests. Please fix.

**Comment by AlyaGomaa** [comment]
CI approved to see if the tests pass or is it a local issue in @zeyadtmi's computer

**Pull request merged**
