### PR TITLE
added description and comments on analysis_direction parameter

### PR DESCRIPTION
**Pull request by Sekhar-Kumar-Dash**
## Changes proposed
I have updated the "usage.md" file to include a description of the analysis_direction parameter. 
I have also updated the "config_parser.py" file to add a short comment on the usage of the parameter

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by AlyaGomaa** [comment]
hello @Sekhar-Kumar-Dash Thank you for the PR
The docs for this parameter in the config/slips.conf file are a bit outdated too, would it be possible to update them to before merging your PR?

**Comment by Sekhar-Kumar-Dash** [comment]
> hello @Sekhar-Kumar-Dash Thank you for the PR The docs for this parameter in the config/slips.conf file are a bit outdated too, would it be possible to update them to before merging your PR?

hey @AlyaGomaa  thank you for reviewing my pull request. Certainly, I will update the this documentation as well

**Comment by Sekhar-Kumar-Dash** [comment]
@AlyaGomaa  I made the required changes please take a look.
Thank you

**Comment by AlyaGomaa** [comment]
Perfect. Thanks for your contribution!

**Comment by Sekhar-Kumar-Dash** [comment]
> Perfect. Thanks for your contribution!

@AlyaGomaa  Thank you so much

**Pull request merged**
