### PR TITLE
added a zeek script irc_feature_extractor.zeek 

### PR DESCRIPTION
**Pull request by HAPPYCODER505**
i added the zeek script named  irc_feature_extractor.zeek  and also updated the  __load__.zeek file.# issue no 213

### CODE REVIEW

**Comment by AlyaGomaa** [comment]
hello @HAPPYCODER505 may I ask you to create the PR to develop, not master, so we can merge your branch faster?

**Comment by AlyaGomaa** [comment]
heyy @HAPPYCODER505 why did you close the issue?

**Comment by HAPPYCODER505** [comment]
sorry

**Comment by AlyaGomaa** [comment]
hey no, all good, will let the checks run then merge your branch

**Pull request closed without merging**
