### PR TITLE
Updated workflows to test and publish macos image

### PR DESCRIPTION
**Pull request by A-atmos**
Issue: #274 

Changes: Updated the workflows to test SLIPS for macos and release the image for macos as mentioned in the issue.

### CODE REVIEW

**Comment by AlyaGomaa** [comment]
Hey @A-atmos  thank for your PR! 
i'll change the pr to master to test your workflow

**Comment by A-atmos** [comment]
hey @AlyaGomaa, the checks are stuck because of some possible misconfigurations. I couldn't locate them by myself, would you mind having a look into this?

**Comment by AlyaGomaa** [comment]
hey @A-atmos yes i'm on it

**Comment by AlyaGomaa** [comment]
hey @A-atmos thanks for your PR!

**Pull request merged**
