### PR TITLE
Http detecting empty connection

### LINKED ISSUE #642: In test_zeek_dataset.py, Sometimes slips triggers this evidence  "Multiple empty HTTP connections to google.com' and sometimes it doesnt
Created by Alya Gomaa via monday.com integration. 🎉

### PR DESCRIPTION
**Pull request by patel-lay**
Closes #642 

## Changes proposed
 Shuffle logs, to test http empty connection

## Steps you followed to test the changes purposed in this PR:

* Underlying assumption is slips is not reading full log file. Moving the logs at the top to test if get detected. If it gets detected, then assumption is correct, and need to understand the issue behind not reading full file. 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Trigger CI testing to verify the claim.

### CODE REVIEW

**Comment by AlyaGomaa** [comment]
hey @patel-lay thanks for your PR
quick note that you can run the same test that run in ci locally by running ./tests/run_all_tests.sh

**Comment by patel-lay** [comment]
Hey @AlyaGomaa, I ran the test locally and passed test without any shuffling. This was way to test if it work fine with CI pipeline, where it previously caused errors.

**Comment by AlyaGomaa** [comment]
ahhh @patel-lay so this means the issue is no longer happening right?

**Comment by patel-lay** [comment]
That is correct, @AlyaGomaa

**Comment by AlyaGomaa** [comment]
Ok awesome! thanks for your effort!

**Pull request closed without merging**
